[package]
name = "knowsql"
version = "0.1.0"
edition = "2021"

[dependencies]
knowsql_bitcask = { workspace = true }

chrono = { workspace = true }
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }
