[package]
name = "knowsql_parser"
edition = "2021"
version.workspace = true
authors.workspace = true
documentation.workspace = true

[dependencies]
nom = { workspace = true }
tracing = { workspace = true } 

