name: build and deploy docker 

on:
  workflow_call:
    inputs:
      latest:
        description: "Tag as latest"
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      latest:
        description: "Tag as latest"
        type: boolean
        required: false
        default: false

jobs:
  build_docker_image:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install Nix
        uses: cachix/install-nix-action@v26
      - name: build docker image
        run: nix build .#dockerImage
      - name: upload docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker_image
          path: result

  push_docker_image:
    name: push docker image
    runs-on: ubuntu-latest
    needs: build_docker_image
    steps:
      - name: download docker_image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker_image
          path: docker_image
      - name: login to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: load docker build
        run: docker load -i ${{ github.workspace }}/docker_image/result
      - name: tag docker image
        run: docker tag knowsql:${{ github.sha }} ghcr.io/gdwr/knowsql:${{ github.sha }}
      - name: push docker image to ghcr
        run: docker push ghcr.io/gdwr/knowsql:${{ github.sha }}
      - name: tag docker image as latest
        if: ${{ inputs.latest }}
        run: docker tag ghcr.io/gdwr/knowsql:${{ github.sha }} ghcr.io/gdwr/knowsql:latest
      - name: push docker image to ghcr as latest
        if: ${{ inputs.latest }}
        run: docker push ghcr.io/gdwr/knowsql:latest
